/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sketchfab (https://sketchfab.com/Sketchfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sketchfab-3d-editor-challenge-littlest-tokyo-d5ca33dacf10459a92a8de25fb362a23
Title: Sketchfab 3D Editor Challenge: Littlest Tokyo
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame,useThree } from '@react-three/fiber'
import {a} from '@react-spring/three'
import townScene from "../assets/3d/town.glb"

const Town = ({isRotating, setIsRotating,setCurrentStage,   ...props}) =>{
  const group = useRef()
  const {gl, viewport} =useThree();
  const { nodes, materials, animations } = useGLTF(
    townScene
  )
  const { actions } = useAnimations(animations, group)
  const lastX =useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor =0.95;
  
  const handlePointerDown = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(true);

    // Calculate the clientX based on whether it's a touch event or a mouse event
    const clientX = event.touches ? event.touches[0].clientX : event.clientX;

    // Store the current clientX position for reference
    lastX.current = clientX;
  };

  const handlePointerUp = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(false);
  };
  const handlePointerMove = (event) => {
    event.stopPropagation();
    event.preventDefault();
    if (isRotating) {
      // If rotation is enabled, calculate the change in clientX position
      const clientX = event.touches ? event.touches[0].clientX : event.clientX;

      // calculate the change in the horizontal position of the mouse cursor or touch input,
      // relative to the viewport's width
      const delta = (clientX - lastX.current) / viewport.width;

      // Update the island's rotation based on the mouse/touch movement
      group.current.rotation.y += delta * 0.01 * Math.PI;

      // Update the reference for the last clientX position
      lastX.current = clientX;

      // Update the rotation speed
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };
  // Handle keydown events
  const handleKeyDown = (event) => {
    if (event.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);

      group.current.rotation.y += 0.005 * Math.PI;
      rotationSpeed.current = 0.007;
    } else if (event.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);

      group.current.rotation.y -= 0.005 * Math.PI;
      rotationSpeed.current = -0.007;
    }
  };

  // Handle keyup events
  const handleKeyUp = (event) => {
    if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
      setIsRotating(false);
    }
  };
  // Touch events for mobile devices
  const handleTouchStart = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
  
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  }
  
  const handleTouchEnd = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }
  
  const handleTouchMove = (e) => {
    e.stopPropagation();
    e.preventDefault();
  
    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;
  
      islandRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }
  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    canvas.addEventListener("touchstart", handleTouchStart);
    canvas.addEventListener("touchend", handleTouchEnd);
    canvas.addEventListener("touchmove", handleTouchMove);
    
    if(isRotating){
        actions['Take 001'].play()
    }else{
        actions['Take 001'].stop()
    }
    // Remove event listeners when component unmounts
    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
      canvas.removeEventListener("touchstart", handleTouchStart);
      canvas.removeEventListener("touchend", handleTouchEnd);
      canvas.removeEventListener("touchmove", handleTouchMove);
    };

  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove,actions,isRotating]);
  useFrame(() => {
    // If not rotating, apply damping to slow down the rotation (smoothly)
    if (!isRotating) {
      // Apply damping factor
      rotationSpeed.current *= dampingFactor;
      

      // Stop rotation when speed is very small
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      group.current.rotation.y += rotationSpeed.current;
    } else {
      // When rotating, determine the current stage based on island's orientation
      const rotation = group.current.rotation.y;
      

      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.8 && normalizedRotation <= 6.8:
          setCurrentStage(1);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 0.9 && normalizedRotation <= 1.7:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 3 && normalizedRotation <= 3.5:
          setCurrentStage(5);
          break;
        default:
          setCurrentStage(null);
      }
    }
  });
  
  return (
    <a.group ref={group} {...props} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[0, 0, 0.0001]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4cd116fc63ca40809810ca0842dc78edfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.normal}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.metalmat}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.normal}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.normal}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.normal}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.normal}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials.normal}
                    skeleton={nodes.Object_18.skeleton}
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.normal}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <group
                    name="Object_6"
                    position={[70.3018, -179.9829, 221.3653]}
                    rotation={[-Math.PI / 2, 0, -3.0543]}
                    scale={0.3157}
                  />
                  <group
                    name="Object_9"
                    position={[-91.8733, 4.9023, -24.3409]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_11"
                    position={[-111.329, 4.9023, -24.3409]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_13"
                    position={[-111.329, 4.9023, -24.3409]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_15"
                    position={[-91.8733, 4.9023, -24.3409]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_17"
                    position={[-91.8733, 4.9023, -24.3409]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_19"
                    position={[-111.329, 4.9023, -24.3409]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object078"
                    position={[76.0747, 163.9373, 118.5971]}
                    rotation={[-Math.PI / 3, 0, 0]}
                    scale={3.0995}>
                    <group name="Object_53" position={[-97.4094, -7.1283, -96.2699]}>
                      <mesh
                        name="Object078_Plastic_Soft_0"
                        
                        
                        geometry={nodes.Object078_Plastic_Soft_0.geometry}
                        material={materials.Plastic_Soft}
                      />
                    </group>
                  </group>
                  <group
                    name="body"
                    position={[41.0543, -198.3637, 208.6787]}
                    rotation={[-Math.PI / 2, 0, 0.9466]}>
                    <group name="Object_56" position={[0, -0.254, 1.8171]}>
                      <mesh
                        name="body_normal_0"
                        
                        
                        geometry={nodes.body_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                    <group name="leaf" position={[-0.0151, 1.3067, 8.0405]}>
                      <group name="Object_59" position={[0.0151, -1.5607, -6.2234]}>
                        <mesh
                          name="leaf_normal_0"
                          
                          
                          geometry={nodes.leaf_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                    <group
                      name="hand2"
                      position={[2.1271, -0.7343, 5.063]}
                      rotation={[0, Math.PI / 3, 0]}>
                      <group name="Object_62" position={[-2.127, 0.4803, -3.2459]}>
                        <mesh
                          name="hand2_normal_0"
                          
                          
                          geometry={nodes.hand2_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                    <group
                      name="hand1"
                      position={[-2.1691, -0.7343, 5.0836]}
                      rotation={[0, -Math.PI / 3, 0]}>
                      <group name="Object_65" position={[2.1691, 0.4803, -3.2665]}>
                        <mesh
                          name="hand1_normal_0"
                          
                          
                          geometry={nodes.hand1_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                    <group name="foot2" position={[2.4278, -0.9229, 2.0197]}>
                      <group name="Object_68" position={[-2.4279, 0.6689, -0.2026]}>
                        <mesh
                          name="foot2_normal_0"
                          
                          
                          geometry={nodes.foot2_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                    <group name="foot1" position={[-2.4906, -0.923, 1.9784]}>
                      <group name="Object_71" position={[2.4907, 0.6689, -0.1613]}>
                        <mesh
                          name="foot1_normal_0"
                          
                          
                          geometry={nodes.foot1_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Object224"
                    position={[50.1282, -163.1572, 190.2581]}
                    rotation={[-Math.PI / 2, 0, -3.0543]}
                    scale={0.3157}
                  />
                  <group
                    name="Object608"
                    position={[-54.3804, 114.4833, -87.5729]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={3.0995}>
                    <group name="Object_75" position={[-55.32, -73.646, -80.3142]}>
                      <mesh
                        name="Object608_metalmat_0"
                        
                        
                        geometry={nodes.Object608_metalmat_0.geometry}
                        material={materials.metalmat}
                      />
                      <mesh
                        name="Object608_paintmat_0"
                        
                        
                        geometry={nodes.Object608_paintmat_0.geometry}
                        material={materials.paintmat}
                      />
                    </group>
                  </group>
                  <group
                    name="Object649"
                    position={[-85.0456, 5.403, -25.4332]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object649_normal_0"
                      
                      
                      geometry={nodes.Object649_normal_0.geometry}
                      material={materials.normal}
                    />
                    <mesh
                      name="Object649_paintmat_0"
                      
                      
                      geometry={nodes.Object649_paintmat_0.geometry}
                      material={materials.paintmat}
                    />
                    <mesh
                      name="Object649_metalmat_0"
                      
                      
                      geometry={nodes.Object649_metalmat_0.geometry}
                      material={materials.metalmat}
                    />
                    <mesh
                      name="Object649_Plastic_Soft_0"
                      
                      
                      geometry={nodes.Object649_Plastic_Soft_0.geometry}
                      material={materials.Plastic_Soft}
                    />
                    <mesh
                      name="Object649_alpha_glass_0"
                      
                      
                      geometry={nodes.Object649_alpha_glass_0.geometry}
                      material={materials.alpha_glass}
                    />
                    <mesh
                      name="Object649_glassmat_0"
                      
                      
                      geometry={nodes.Object649_glassmat_0.geometry}
                      material={materials.glassmat}
                    />
                    <mesh
                      name="Object649_Material_#5511_0"
                      
                      
                      geometry={nodes['Object649_Material_#5511_0'].geometry}
                      material={materials.Material_5511}
                    />
                    <mesh
                      name="Object649_Material_#5512_0"
                      
                      
                      geometry={nodes['Object649_Material_#5512_0'].geometry}
                      material={materials.Material_5512}
                    />
                    <mesh
                      name="Object649_glass_transp_0"
                      
                      
                      geometry={nodes.Object649_glass_transp_0.geometry}
                      material={materials.glass_transp}
                    />
                    <mesh
                      name="Object649_interiors_0"
                      
                      
                      geometry={nodes.Object649_interiors_0.geometry}
                      material={materials.interiors}
                    />
                    <mesh
                      name="Object649_alpha_0"
                      
                      
                      geometry={nodes.Object649_alpha_0.geometry}
                      material={materials.alpha}
                    />
                  </group>
                  <group
                    name="wire7"
                    position={[53.4426, -91.07, 179.8325]}
                    rotation={[-1.5336, 0, 0]}>
                    <group name="Object_91" position={[-138.4882, 205.2657, 96.473]}>
                      <mesh
                        name="wire7_normal_0"
                        
                        
                        geometry={nodes.wire7_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object674"
                    position={[-85.0456, 5.403, -25.4332]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object674_outline_0"
                      
                      
                      geometry={nodes.Object674_outline_0.geometry}
                      material={materials.outline}
                    />
                    <mesh
                      name="Object674_outline_0_1"
                      
                      
                      geometry={nodes.Object674_outline_0_1.geometry}
                      material={materials.outline}
                    />
                  </group>
                  <group
                    name="Object675"
                    position={[85.4623, -196.5193, -246.3859]}
                    rotation={[-Math.PI / 2, 0, 3.1126]}>
                    <group name="Object_97" position={[0, 0, 76.4302]}>
                      <mesh
                        name="Object675_metalmat_0"
                        
                        
                        geometry={nodes.Object675_metalmat_0.geometry}
                        material={materials.metalmat}
                      />
                      <mesh
                        name="Object675_paintmat_0"
                        
                        
                        geometry={nodes.Object675_paintmat_0.geometry}
                        material={materials.paintmat}
                      />
                      <mesh
                        name="Object675_glassmat_0"
                        
                        
                        geometry={nodes.Object675_glassmat_0.geometry}
                        material={materials.glassmat}
                      />
                      <mesh
                        name="Object675_outline_0"
                        
                        
                        geometry={nodes.Object675_outline_0.geometry}
                        material={materials.outline}
                      />
                    </group>
                    <group name="Object680" position={[-12.8873, 0, 8.351]}>
                      <group name="Object_103" position={[12.8873, 0, 68.0791]}>
                        <mesh
                          name="Object680_metalmat_0"
                          
                          
                          geometry={nodes.Object680_metalmat_0.geometry}
                          material={materials.metalmat}
                        />
                      </group>
                    </group>
                    <group name="Object681" position={[14.2896, 0, 8.351]}>
                      <group name="Object_106" position={[12.8873, 0, 68.0791]}>
                        <mesh
                          name="Object681_metalmat_0"
                          
                          
                          geometry={nodes.Object681_metalmat_0.geometry}
                          material={materials.metalmat}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Object532"
                    position={[-29.2579, -38.7312, -7.815]}
                    rotation={[-Math.PI / 2, 0, -0.6981]}
                    scale={3.0995}>
                    <group
                      name="Object_109"
                      position={[-17.7068, -77.4483, -30.8818]}
                      rotation={[0, 0, 0.6981]}>
                      <mesh
                        name="Object532_normal_0"
                        
                        
                        geometry={nodes.Object532_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object531"
                    position={[-29.6963, -38.7312, -8.1829]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={3.0995}>
                    <group name="Object_112" position={[-63.347, -47.9471, -30.8818]}>
                      <mesh
                        name="Object531_normal_0"
                        
                        
                        geometry={nodes.Object531_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object689"
                    position={[-245.5247, -161.7815, -259.3083]}
                    rotation={[-1.627, -0.0668, -0.7]}>
                    <group name="Object_115" rotation={[0, 0, 0.6981]}>
                      <mesh
                        name="Object689_metalmat_0"
                        
                        
                        geometry={nodes.Object689_metalmat_0.geometry}
                        material={materials.metalmat}
                      />
                    </group>
                  </group>
                  <group
                    name="Plane001"
                    position={[-101.4398, 184.595, -141.8276]}
                    rotation={[-Math.PI / 2, 0, -0.1399]}>
                    <group name="Object_118" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane001_normal_0"
                        
                        
                        geometry={nodes.Plane001_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Plane003"
                    position={[-95.3112, 184.595, -140.9647]}
                    rotation={[Math.PI / 2, 0, 0.1399]}
                    scale={-1}>
                    <group name="Object_121" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane003_normal_0"
                        
                        
                        geometry={nodes.Plane003_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object688"
                    position={[170.3345, 105.0851, 196.5618]}
                    rotation={[-Math.PI / 2, 0, 1.8919]}
                  />
                  <group
                    name="Plane104"
                    position={[-83.1707, 184.595, -140.3799]}
                    rotation={[-Math.PI / 2, 0, 0.3]}>
                    <group name="Object_125" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane104_normal_0"
                        
                        
                        geometry={nodes.Plane104_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Plane103"
                    position={[-77.258, 184.595, -142.2088]}
                    rotation={[Math.PI / 2, 0, -0.3]}
                    scale={-1}>
                    <group name="Object_128" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane103_normal_0"
                        
                        
                        geometry={nodes.Plane103_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object687"
                    position={[126.5511, 7.1028, -162.4545]}
                    rotation={[-Math.PI / 2, 0, -2.0152]}
                  />
                  <group
                    name="Plane105"
                    position={[133.4812, 48.2693, -68.2758]}
                    rotation={[-Math.PI / 2, 0, -1.8917]}>
                    <group name="Object_132" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane105_normal_0"
                        
                        
                        geometry={nodes.Plane105_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object697"
                    position={[112.712, -129.2229, 159.7021]}
                    rotation={[-Math.PI / 2, 0, 2.5161]}
                  />
                  <group
                    name="Plane106"
                    position={[131.5287, 48.2693, -62.4028]}
                    rotation={[Math.PI / 2, 0, 1.8917]}
                    scale={-1}>
                    <group name="Object_136" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane106_normal_0"
                        
                        
                        geometry={nodes.Plane106_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Plane108"
                    position={[148.0822, 111.7081, 190.1595]}
                    rotation={[-Math.PI / 2, 0, 2.969]}>
                    <group name="Object_139" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane108_normal_0"
                        
                        
                        geometry={nodes.Plane108_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object698"
                    position={[75.7513, 32.1982, -225.2473]}
                    rotation={[-Math.PI / 2, 0, -1.7224]}
                  />
                  <group
                    name="Plane107"
                    position={[141.9851, 111.7081, 189.0963]}
                    rotation={[Math.PI / 2, 0, -2.969]}
                    scale={-1}>
                    <group name="Object_143" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane107_normal_0"
                        
                        
                        geometry={nodes.Plane107_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object699"
                    position={[452.97, 28.8864, -125.9429]}
                    rotation={[-Math.PI / 2, 0, -2.6237]}
                  />
                  <group
                    name="Plane109"
                    position={[172.1029, 108.3963, 188.5539]}
                    rotation={[-Math.PI / 2, 0, 2.0676]}>
                    <group name="Object_147" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane109_normal_0"
                        
                        
                        geometry={nodes.Plane109_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Plane110"
                    position={[169.1532, 108.3963, 183.113]}
                    rotation={[Math.PI / 2, 0, -2.0676]}
                    scale={-1}>
                    <group name="Object_150" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane110_normal_0"
                        
                        
                        geometry={nodes.Plane110_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Plane111"
                    position={[38.8253, 198.5967, 68.5639]}
                    rotation={[1.5708, 0, -0.1346]}
                    scale={-1}>
                    <group name="Object_153" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane111_normal_0"
                        
                        
                        geometry={nodes.Plane111_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Plane112"
                    position={[32.6922, 198.5967, 69.3944]}
                    rotation={[-Math.PI / 2, 0, 0.1346]}>
                    <group name="Object_156" position={[-0.9648, -3.6057, -2.0904]}>
                      <mesh
                        name="Plane112_normal_0"
                        
                        
                        geometry={nodes.Plane112_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object700"
                    position={[246.5585, 21.1045, -12.2545]}
                    rotation={[-Math.PI / 2, 0, -1.7407]}
                  />
                  <group
                    name="Object704"
                    position={[-134.8808, -36.7013, -123.5831]}
                    rotation={[-1.5763, 0.0104, -0.0184]}>
                    <group name="Object_160" position={[49.8352, -98.1498, 42.1042]}>
                      <mesh
                        name="Object704_Plastic_Soft_0"
                        
                        
                        geometry={nodes.Object704_Plastic_Soft_0.geometry}
                        material={materials.Plastic_Soft}
                      />
                      <mesh
                        name="Object704_metalmat_0"
                        
                        
                        geometry={nodes.Object704_metalmat_0.geometry}
                        material={materials.metalmat}
                      />
                    </group>
                  </group>
                  <group
                    name="wire1"
                    position={[11.3489, -53.562, -65.6722]}
                    rotation={[-1.7482, -0.0948, 0.1408]}>
                    <group
                      name="Object_164"
                      position={[-101.137, -36.7321, 53.0097]}
                      rotation={[0.1889, 0, -0.1427]}>
                      <mesh
                        name="wire1_Plastic_Soft_0"
                        
                        
                        geometry={nodes.wire1_Plastic_Soft_0.geometry}
                        material={materials.Plastic_Soft}
                      />
                    </group>
                  </group>
                  <group
                    name="wire2"
                    position={[51.8263, -43.9745, -45.5409]}
                    rotation={[-1.6072, -0.0352, -0.8027]}>
                    <group
                      name="Object_167"
                      position={[-80.7067, -112.3596, 49.3774]}
                      rotation={[0, 0, 0.802]}>
                      <mesh
                        name="wire2_Plastic_Soft_0"
                        
                        
                        geometry={nodes.wire2_Plastic_Soft_0.geometry}
                        material={materials.Plastic_Soft}
                      />
                    </group>
                    <group
                      name="Object081"
                      position={[3.6537, -65.195, -24.4929]}
                      rotation={[0.0434, 0.0122, -2.8676]}
                      scale={3.0995}>
                      <group
                        name="Object_170"
                        position={[-91.8607, 2.8684, -19.1243]}
                        rotation={[0, 0, -0.5194]}>
                        <mesh
                          name="Object081_normal_0"
                          
                          
                          geometry={nodes.Object081_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                    <group
                      name="Object332"
                      position={[3.7995, -102.1622, -21.4303]}
                      rotation={[0.0514, -0.0779, -2.349]}
                      scale={3.0995}>
                      <group name="Object_173" position={[-78.6679, -54.7354, -19.1243]}>
                        <mesh
                          name="Object332_normal_0"
                          
                          
                          geometry={nodes.Object332_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                    <group
                      name="Object682"
                      position={[0.5415, -22.6985, -18.8032]}
                      rotation={[0.076, -0.0303, -1.6406]}
                      scale={3.0995}>
                      <group name="Object_176" position={[-78.6679, -54.7354, -19.1243]}>
                        <mesh
                          name="Object682_normal_0"
                          
                          
                          geometry={nodes.Object682_normal_0.geometry}
                          material={materials.normal}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="wire3"
                    position={[-3.7682, -84.4429, -56.369]}
                    rotation={[-Math.PI / 2, 0, 0.0687]}>
                    <group
                      name="Object_179"
                      position={[-83.2087, -25.2856, 89.8458]}
                      rotation={[0, 0, -0.0687]}>
                      <mesh
                        name="wire3_normal_0"
                        
                        
                        geometry={nodes.wire3_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="wire4"
                    position={[50.9213, -99.0129, -52.2727]}
                    rotation={[-1.5588, 0.0717, -0.1658]}>
                    <group
                      name="Object_182"
                      position={[-129.6918, -48.8609, 104.4159]}
                      rotation={[0, 0, 0.1654]}>
                      <mesh
                        name="wire4_normal_0"
                        
                        
                        geometry={nodes.wire4_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="wire5"
                    position={[77.6724, -109.8137, -59.7034]}
                    rotation={[-1.5566, -0.0487, 0.2848]}>
                    <group
                      name="Object_185"
                      position={[-165.7961, 12.7773, 115.2166]}
                      rotation={[0, 0, -0.2845]}>
                      <mesh
                        name="wire5_normal_0"
                        
                        
                        geometry={nodes.wire5_normal_0.geometry}
                        material={materials.normal}
                      />
                    </group>
                  </group>
                  <group
                    name="Object705"
                    position={[-85.0456, 5.403, -25.4332]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object705_Material_#5516_0"
                      
                      
                      geometry={nodes['Object705_Material_#5516_0'].geometry}
                      material={materials.Material_5516}
                    />
                  </group>
                  <group
                    name="treezzzzz"
                    position={[-173.3887, -142.4725, 79.9291]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                      name="Object619"
                      position={[80.2085, -105.995, -2.985]}
                      rotation={[-0.3198, 0.8602, -1.3711]}
                      scale={0.7915}>
                      <group name="Object_191" position={[0.6685, 3.9686, 17.9867]}>
                        <mesh
                          name="Object619_alpha_0"
                          
                          
                          geometry={nodes.Object619_alpha_0.geometry}
                          material={materials.alpha_0}
                        />
                      </group>
                    </group>
                    <group
                      name="Object620"
                      position={[-62.0259, -105.9456, -1.4281]}
                      rotation={[-0.3198, 0.8602, -1.3711]}
                      scale={0.7915}>
                      <group name="Object_194" position={[0.6685, 3.9686, 17.9867]}>
                        <mesh
                          name="Object620_alpha_0"
                          
                          
                          geometry={nodes.Object620_alpha_0.geometry}
                          material={materials.alpha_0}
                        />
                      </group>
                    </group>
                    <group
                      name="Object621"
                      position={[-81.0531, 105.3857, -0.6635]}
                      rotation={[-0.3198, 0.8602, -1.3711]}
                      scale={0.7915}>
                      <group name="Object_197" position={[0.6685, 3.9686, 17.9867]}>
                        <mesh
                          name="Object621_alpha_0"
                          
                          
                          geometry={nodes.Object621_alpha_0.geometry}
                          material={materials.alpha_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Object622"
                    position={[-85.0456, 5.403, -25.4332]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object622_alpha_0"
                      
                      
                      geometry={nodes.Object622_alpha_0.geometry}
                      material={materials.alpha_0}
                    />
                  </group>
                  <group
                    name="Object706"
                    position={[26.3742, -164.4733, 185.1065]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_202" position={[-111.4198, 210.5397, 169.8763]}>
                      <mesh
                        name="Object706_Material_#5518_0"
                        
                        
                        geometry={nodes['Object706_Material_#5518_0'].geometry}
                        material={materials.Material_5518}
                      />
                    </group>
                  </group>
                  <group
                    name="Object707"
                    position={[26.3742, -163.1413, 185.1065]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_205" position={[-111.4198, 210.5397, 168.5443]}>
                      <mesh
                        name="Object707_Material_#5518_0"
                        
                        
                        geometry={nodes['Object707_Material_#5518_0'].geometry}
                        material={materials.Material_5518}
                      />
                    </group>
                  </group>
                  <group
                    name="Object708"
                    position={[-121.5094, 153.7408, 54.2089]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_208" position={[-111.4198, 210.5397, 169.8763]}>
                      <mesh
                        name="Object708_Material_#5518_0"
                        
                        
                        geometry={nodes['Object708_Material_#5518_0'].geometry}
                        material={materials.Material_5518}
                      />
                    </group>
                  </group>
                  <group
                    name="Object709"
                    position={[-121.5094, 155.0729, 54.2089]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_211" position={[-111.4198, 210.5397, 168.5443]}>
                      <mesh
                        name="Object709_Material_#5518_0"
                        
                        
                        geometry={nodes['Object709_Material_#5518_0'].geometry}
                        material={materials.Material_5518}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  )
}



export default Town;